# Generated by Django 4.2.11 on 2026-06-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagan_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
