# Generated by Django 4.2.11 on 2025-10-02 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaysRadar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeContratRadar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RegionRadar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radar.paysradar')),
            ],
        ),
        migrations.CreateModel(
            name='EmploiRadar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('logo', models.URLField(null=True)),
                ('mini_description', models.TextField(null=True)),
                ('date_publication', models.DateField()),
                ('date_limite', models.DateField(null=True)),
                ('lien_candidature', models.URLField()),
                ('nom_entreprise', models.CharField(max_length=150)),
                ('provenance', models.CharField(max_length=200)),
                ('mail_candidature', models.EmailField(max_length=150)),
                ('emploi_contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radar.typecontratradar')),
                ('emploi_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radar.regionradar')),
            ],
        ),
    ]
