# Generated by Django 4.2.11 on 2025-10-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploiradar',
            name='emplacement',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='emploiradar',
            name='mail_candidature',
            field=models.EmailField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='typecontratradar',
            name='nom',
            field=models.CharField(max_length=50),
        ),
    ]
