# Generated by Django 4.2.11 on 2025-10-02 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0002_emploiradar_emplacement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploiradar',
            name='emploi_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='radar.regionradar'),
        ),
    ]
