# Generated by Django 4.2.11 on 2025-10-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0003_alter_emploiradar_emploi_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploiradar',
            name='lien_candidature',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='emploiradar',
            name='logo',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
