# Generated by Django 4.2.11 on 2026-06-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_name', models.CharField(default='Bakeli Tech', max_length=255)),
                ('description', models.TextField(blank=True, default="Bakeli Tech veut accompagner tout type d'individu vers l'informatique.")),
                ('schedules', models.TextField(blank=True, default='Lundi au Vendredi: 9h - 18h\nSamedi: 9h - 13h')),
                ('training_catalog', models.TextField(blank=True, help_text='Catalogue des formations en texte ou Markdown')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Base de connaissances Chatbot',
                'verbose_name_plural': 'Base de connaissances Chatbot',
            },
        ),
    ]
