# Generated by Django 4.2.11 on 2026-07-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0002_chatbotknowledge'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etablissement_nom', models.CharField(default='Bakeli School of Technology', max_length=255, verbose_name="Nom de l'établissement")),
                ('etablissement_description', models.TextField(default='Centre de formation professionnelle diplômante et certifiante au Sénégal.', verbose_name="Description de l'établissement")),
                ('etablissement_site', models.URLField(default='https://bakeli.tech', verbose_name='Site web')),
                ('etablissement_inscription', models.URLField(default='https://bakeli.tech/inscription', verbose_name="Lien d'inscription")),
                ('catalogue_formations', models.TextField(help_text='Décrivez chaque formation, ses durées et son lien. Le bot utilisera ce texte pour répondre aux prospects.', verbose_name='Catalogue des formations (texte libre)')),
                ('horaires', models.TextField(default='Cours en présentiel du lundi au vendredi. Pas de cours le week-end.', help_text='Informations sur les horaires, jours de cours, modalités (présentiel, en ligne).', verbose_name='Horaires et disponibilités')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Base de Connaissances du Bot',
                'verbose_name_plural': 'Base de Connaissances du Bot',
            },
        ),
        migrations.DeleteModel(
            name='ChatbotKnowledge',
        ),
    ]
