# Generated by Django 4.2.11 on 2026-07-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0004_add_conversation_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sentiment_label',
            field=models.CharField(blank=True, choices=[('positive', 'Positive (Hot Lead)'), ('neutral', 'Neutral'), ('lost_lead', 'Lost Lead (Abandon)'), ('bot_stuck', 'Bot Stuck (Impasse)'), ('angry', 'Angry (Mécontent)')], max_length=15, null=True),
        ),
    ]
