# Generated by Django 4.2.11 on 2026-07-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0005_alter_message_sentiment_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationstate',
            name='statut_prospect',
            field=models.CharField(choices=[('positive', 'Chaud (Hot Lead)'), ('neutral', 'Froid / En exploration'), ('lost_lead', 'Perdu / Désintéressé'), ('bot_stuck', 'Bloqué (Impasse bot)'), ('angry', 'Irrité / Mécontent')], db_index=True, default='neutral', max_length=15),
        ),
        migrations.AddField(
            model_name='conversationstate',
            name='statut_score',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='conversationstate',
            name='statut_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
