# Generated by Django 4.2.11 on 2026-07-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0006_conversationstate_statut_prospect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], default='user', max_length=10),
        ),
    ]
