# Generated by Django 4.2.11 on 2026-07-13 15:01

import datetime
from django.db import migrations
from django.utils import timezone

def migrate_bot_history(apps, schema_editor):
    ConversationState = apps.get_model('whatsapp_bot', 'ConversationState')
    Message = apps.get_model('whatsapp_bot', 'Message')
    
    for state in ConversationState.objects.all():
        history = state.history
        phone_number = state.phone_number
        if not history:
            continue
        
        # Pour éviter de tout mettre à la même seconde, on simule un ordre temporel
        base_time = state.updated_at if state.updated_at else timezone.now()
        
        for idx, msg in enumerate(history):
            role = msg.get('role')
            content = msg.get('content')
            
            if role == 'assistant' and content:
                # On simule un léger décalage temporel pour garder l'ordre dans le dashboard
                simulated_time = base_time + datetime.timedelta(seconds=idx)
                Message.objects.create(
                    phone_number=phone_number,
                    message_text=content,
                    role='bot',
                    processed=True,
                    timestamp=simulated_time
                )


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0007_message_role'),
    ]

    operations = [
        migrations.RunPython(migrate_bot_history),
    ]
